basler_params:
  -
    name: AcquisitionFrameRate
    type: float
    value: 5.0
  -
    name: ExposureTime
    type: float
    value: 10000.0
  -
    name: AcquisitionMode
    type: enum
    value: Continuous
  -
    name: OverlapMode
    type: enum
    value: 'Off'
  -
    name: ExposureAuto
    type: enum
    value: Continuous
  -
    name: GainAuto
    type: enum
    value: 'Off'
  -
    name: Gain
    type: float
    value: 10.0
  -
    name: TriggerMode
    type: enum
    value: 'On'
  -
    name: TriggerSource
    type: enum
    value: Line2
  -
    name: LineSelector
    type: enum
    value: Line2
  -
    name: LineMode
    type: enum
    value: Input
